### ISSUE TITLE
S3 expire_files not checking prefix?

### ISSUE THREAD

**Issue by pelcasandra** [janko/tus-ruby-server#13]
It seems that the method to expire files is not checking the prefix. This can potentially expire files outside the scope of tus. 

I believe `bucket.objects` should be `bucket.objects(prefix: @prefix)` here:
https://github.com/janko/tus-ruby-server/blob/master/lib/tus/storage/s3.rb#L212

And also `bucket.multipart_uploads` should be `bucket.multipart_uploads.prefix(prefix: @prefix)` here:
 https://github.com/janko/tus-ruby-server/blob/master/lib/tus/storage/s3.rb#L218

**Comment by janko** [comment]
Oh, you're totally right, good catch. I think I can get it fixed by the end of this week, though I may not find time until Friday. If you would like to send a PR for this yourself, that would be great 😃(you seem to already know the solutions)
