### ISSUE TITLE
error 400 in local

### ISSUE THREAD

**Issue by adrihildasukasa** [janko/tus-ruby-server#15]
sorry i want to ask, i want to use tus on my local development
first I add gem "tus-server", "~> 2.0" to my gemfile
and i add this to my routes.rb 
Rails.application.routes.draw do
  mount Tus::Server => "/files"
end

when my IOS hit my localhost:3000/files they get error code 400

can you help me?

**Comment by janko** [comment]
What is the body from that response? `400 Bad Request` means that the client sent invalid parameters to the server, in which case the response body would contain the error message.

**Comment by adrihildasukasa** [comment]
> What is the body from that response? `400 Bad Request` means that the client sent invalid parameters to the server, in which case the response body would contain the error message.

okay thanks, already solve by 
add metadata:  filename: file.name,filetype: file.type
it is possible to add filename and filetype in request header not in metadata????

**Comment by janko** [comment]
No, as that’s not part of the tus.io protocol.
