### ISSUE TITLE
dynamic storage adapters

### ISSUE THREAD

**Issue by jalevin** [janko/tus-ruby-server#16]
For security purposes, I have different buckets with different encryption keys that are separated per client in my app. As clients sign up, they get a bucket and a key specific to them. Is it possible to create new s3 adapters on the fly?

**Comment by janko** [comment]
I believe you could make it work by subclassing `Tus::Server` and overriding the `#storage` method. There you would have access to the request object, so you can decide the storage based on request headers if that's what you had in mind.

```rb
class MyTusServer < Tus::Server
  def storage
    request #=> #<Rack::Request>
    Tus::Storage::S3.new(...) # generate options based on request headers
  end
end
```

**Comment by jalevin** [comment]
Perfect. For anyone else interested. I mount the route inside a lambda that checks user permissions. Then I pass the prefix in via a session variable.

config/routes.rb
```
authenticate :user, lambda { |u| u.admin? || u.superadmin? } do
	mount UploadServer => 'files'
	get "upload" => 'uploader#index', as: 'upload_asset'
	post "upload" => 'uploader#create', as: 'create_asset'
end
```

config/initializers/tus.rb
```
class UploadServer < Tus::Server
  def storage
    request #=> #<Roda::Request>
    request.headers #=> hash of request headers

    prefix = session['prefix']
    Tus::Server.opts[:storage] = Tus::Storage::S3.new(prefix: prefix, ...)
  end
end
```
