### ISSUE TITLE
Full file SHA256 checksum?

### ISSUE THREAD

**Issue by dup2** [janko/tus-ruby-server#25]
We are evaluating this server for large file uploads and would need to have the full file SHA256 checksum in the end for validation. Doing this only after the upload is finished is ugly and a performance issue (i.e. for a 50GB file).

As I understand the tus protocol, checksumming is only done for chunk verification - is there any way to get a full file checksum after the last chunk? Or any hooks we could use to compute a kind of "running" checksum while chunks are uploaded?

**Comment by janko** [comment]
If all individual chunks passed checksum validation, doesn't that mean the whole upload passed it too? Why is additionally validating the total checksum at the end needed?

**Comment by dup2** [comment]
Thanks for the fast reply!

It is meant for post-processing and later reference - i.e. we keep the checksum in a journal, use it for signing the document etc in the application. It is not meant for validating the upload but rather for later usage in the application where it would be very handy to have it computed on the fly instead of having to do a full pass later on when the file is uploaded.

We did use the nginx-upload-module which provides this (but does not provide chunk based resumable upload) so I'm looking into a way to provide this as well.

**Comment by janko** [comment]
Aha, I understand. For the request body IO objects that are rewindable (depends on the web server and its configuration), a hook triggered [after upload](https://github.com/janko/tus-ruby-server/blob/44746ade89c4c550913e18f613997f2f519b9019/lib/tus/server.rb#L164) might work. The only thing is that I don't know how you would resume calculating the hash between requests.

Alternatively, it could be possible to override the `#patch_file` method on the storage object, and update the info hash passed as the argument there after upload.

**Comment by dup2** [comment]
Thanks for this information - is the hook "after_upload" already available? 

Resume calculating the hash would work by dumping/reading the OpenSSL SHA256_CTX context but I see now that with ruby, I can not get hold of it in an easy way..

**Comment by dup2** [comment]
I implemented a custom storage backend for all this which was the easiest way IMHO.

Resumable SHA256 can be achieved by using FFI and dumping/reading the memory of the SHA256_CTX  into a file to resume processing, it obviously depends on chunk order.

Thanks for your support and implementation of the server!
